=== tvd12/cocos2dx-v3/runtime-New_configuration/ComplexExample/resources/xml/xsd/view_2_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.tvd.com/tools"  
		xmlns="http://www.tvd.com/tools" 
		xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		elementFormDefault="qualified">
	<xs:element name="view">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="position-name" maxOccurs="1" minOccurs="1" />
				<xs:element ref="position" maxOccurs="1" minOccurs="1" />
				<xs:element ref="define-path" maxOccurs="1" minOccurs="1" />
				<xs:element ref="parameters-path" maxOccurs="1" minOccurs="1" />
				<xs:element ref="images-inputpath" maxOccurs="1" minOccurs="1" />
				<xs:element ref="images-path" maxOccurs="1" minOccurs="1" />
				<xs:element ref="xibcontainer-path" maxOccurs="1" minOccurs="1" />
				<xs:element ref="screencontainer-path" maxOccurs="1" minOccurs="1" />
				<xs:element ref="androidcontainer-path" maxOccurs="1" minOccurs="1" />
				<xs:element ref="class-path" maxOccurs="1" minOccurs="1" />
				<xs:element ref="parameter" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="background-image" maxOccurs="1" minOccurs="0"/>
				<xs:element ref="exit-image" maxOccurs="1" minOccurs="0" />
				<xs:element ref="sprites" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="labels"  maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="menus" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="menuitems" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="tables" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="resource" maxOccurs="1" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="background-name" type="xs:string" use="optional" />
			<xs:attribute name="type" type="xs:string" use="required" />
			<xs:attribute name="size" type="pointtype" use="required" />
			<xs:attribute name="exitable" type="xs:boolean" use="optional" />
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="position-name">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
					<xs:attribute name="unlocated" type="xs:boolean" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="position">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string"> 
					<xs:attribute name="value" type="pointtype" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="define-path">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameters-path">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="images-inputpath">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="images-path">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="xibcontainer-path">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
					<xs:attribute name="used" type="xs:boolean" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
		<xs:element name="screencontainer-path">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
					<xs:attribute name="used" type="xs:boolean" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="androidcontainer-path">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />	
					<xs:attribute name="used" type="xs:boolean" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="class-path">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="type" type="xs:string" use="required" />
					<xs:attribute name="kind" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="normal" />
								<xs:enumeration value="ref" />
								<xs:enumeration value="pointer" />
								<xs:enumeration value="const-normal" />
								<xs:enumeration value="const-ref" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="imagetype">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="background" 
					type="xs:boolean" use="optional" />
				<xs:attribute name="id" type="xs:string" use="optional" />
				<xs:attribute name="phony-path" type="xs:string" />
				<xs:attribute name="real-path" type="xs:string" use="optional" />
				<xs:attribute name="width" type="xs:float" use="optional" />
				<xs:attribute name="height" type="xs:float" use="optional" />
				<xs:attribute name="location-in-interfacebuilder" 
					type="pointtype" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="image">
		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="imagetype" />
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="background-image">
		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="imagetype" />
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="exit-image">
		<xs:complexType>
			<xs:attribute name="position" type="pointtype" use="required" />
			<xs:attribute name="location-in-interfacebuilder" 
					type="pointtype" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="sprites">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sprite" maxOccurs="unbounded" minOccurs="1" />
				<xs:element ref="next" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="array" type="xs:boolean" use="optional" />
			<xs:attribute name="length" type="xs:integer" use="optional" />
			<xs:attribute name="comment" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="menuitems">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="menuitem" maxOccurs="unbounded" minOccurs="1" />
				<xs:element ref="next" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="array" type="xs:boolean" use="optional" />
			<xs:attribute name="length" type="xs:integer" use="optional" />
			<xs:attribute name="comment" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="menus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="menu" maxOccurs="unbounded" minOccurs="1" />
				<xs:element ref="next" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="array" type="xs:boolean" use="optional" />
			<xs:attribute name="length" type="xs:integer" use="optional" />
			<xs:attribute name="comment" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="tables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="table" maxOccurs="unbounded" minOccurs="1" />
				<xs:element ref="next" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="array" type="xs:boolean" use="optional" />
			<xs:attribute name="length" type="xs:integer" use="optional" />
			<xs:attribute name="comment" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="labels">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" maxOccurs="unbounded" minOccurs="1" />
				<xs:element ref="next" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="array" type="xs:boolean" use="optional" />
			<xs:attribute name="length" type="xs:integer" use="optional" />
			<xs:attribute name="comment" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="sprite">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="advancedgroup" />
				<xs:element ref="image" maxOccurs="1" minOccurs="0" />
				<xs:element ref="sprites" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="labels" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="menus" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="menuitems" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="tables" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="progressbar" maxOccurs="1" minOccurs="0" />
			</xs:sequence>
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="menuitem">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="advancedgroup" />
				<xs:element name="sprites" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="sprite" maxOccurs="3" minOccurs="2" />
						</xs:sequence>
						<xs:attribute name="array" type="xs:boolean" use="optional" />
						<xs:attributeGroup ref="template" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="menu">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="advancedgroup" />
				<xs:element ref="menuitems" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="table">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="position-name" maxOccurs="1" minOccurs="1" />
				<xs:element ref="size-name" maxOccurs="1" minOccurs="0" />
				<xs:element ref="anchorpoint" maxOccurs="1" minOccurs="0" />
				<xs:element ref="position" maxOccurs="1" minOccurs="0" />
				<xs:element ref="size" maxOccurs="1" minOccurs="1" />
				<xs:element ref="z-index" maxOccurs="1" minOccurs="0" />
				<xs:element ref="image" maxOccurs="1" minOccurs="1" />
				<xs:element ref="cell" maxOccurs="1" minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="rows" type="xs:integer" use="required" />
			<xs:attribute name="columns" type="xs:integer" use="required" />
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="cell">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="position" maxOccurs="1" minOccurs="0" />
				<xs:element ref="size" maxOccurs="1" minOccurs="0" />
				<xs:element ref="image" maxOccurs="1" minOccurs="1" />
				<xs:element ref="sprites" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="labels" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="menuitems" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="menus" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="tables" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="label">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text" maxOccurs="1" minOccurs="1" />
				<xs:element ref="font" maxOccurs="1" minOccurs="1" />
				<xs:element ref="font-color" maxOccurs="1" minOccurs="1" />
				<xs:element ref="font-size" maxOccurs="1" minOccurs="1" />
				<xs:element ref="position-name" maxOccurs="1" minOccurs="1" />
				<xs:element ref="anchorpoint" maxOccurs="1" minOccurs="0" />
				<xs:element ref="position" maxOccurs="1" minOccurs="1" />
				<xs:element ref="location-in-interfacebuilder" maxOccurs="1" minOccurs="1" />
				<xs:element ref="z-index" maxOccurs="1" minOccurs="0" />
			</xs:sequence>
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="progressbar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type" maxOccurs="1" minOccurs="1" />
				<xs:element ref="mid-point" maxOccurs="1" minOccurs="1" />
				<xs:element ref="bar-change-rate" maxOccurs="1" minOccurs="1" />
				<xs:element ref="percent" maxOccurs="1" minOccurs="1" />
				<xs:element ref="position-name" maxOccurs="1" minOccurs="1" />
				<xs:element ref="anchorpoint" maxOccurs="1" minOccurs="1" />
				<xs:element ref="sprite" maxOccurs="1" minOccurs="1" />
			</xs:sequence>
			<xs:attributeGroup ref="template" />
			<xs:attributeGroup ref="advancedattributegroup" />
		</xs:complexType>
	</xs:element>
	<xs:element name="next">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="position" maxOccurs="1" minOccurs="1" />
				<xs:element ref="image" maxOccurs="1" minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="comment" type="xs:string" use="optional" />
			<xs:attribute name="visible" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="resource">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="image" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="comment" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="size-name">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchorpoint">
		<xs:complexType>
			<xs:attribute name="value" type="pointtype" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="pointtype">
		<xs:restriction base="xs:string">
			<xs:pattern value="default|[-+]?(\d*[.])?\d+, [-+]?(\d*[.])?\d+" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="text">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
					<xs:attribute name="varname" type="vartype" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="font">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="family" type="xs:string" use="optional" />
					<xs:attribute name="varname" type="vartype" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="font-color">
		<xs:complexType>
			<xs:attribute name="red" type="xs:unsignedByte" use="required" />
			<xs:attribute name="green" type="xs:unsignedByte" use="required" />
			<xs:attribute name="blue" type="xs:unsignedByte" use="required" />
			<xs:attribute name="alpha" type="xs:unsignedByte" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="z-index">
		<xs:complexType>
			<xs:attribute name="value" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="font-size">
		<xs:complexType>
			<xs:attribute name="value" type="xs:float" use="required" />
			<xs:attribute name="varname" type="vartype" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="cell-position">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="size">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="pointtype" use="required" />
				</xs:extension>
			</xs:simpleContent> 
		</xs:complexType>
	</xs:element>
	<xs:element name="cell-size">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="location-in-interfacebuilder">
		<xs:complexType>
			<xs:attribute name="value" type="pointtype" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="mid-point">
		<xs:complexType>
			<xs:attribute name="value" type="pointtype" use="required" />
			<xs:attribute name="varname" type="vartype" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="bar-change-rate">
		<xs:complexType>
			<xs:attribute name="value" type="pointtype" use="required" />
			<xs:attribute name="varname" type="vartype" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="percent">
		<xs:complexType>
			<xs:attribute name="value" type="xs:float" use="required" />
			<xs:attribute name="varname" type="vartype" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:complexType>
		<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="template">
		<xs:attribute name="comment" type="xs:string" use="optional" />
		<xs:attribute name="visible" type="xs:boolean" use="optional" />
		<xs:attribute name="template-name" type="xs:string" use="optional" />
		<xs:attribute name="template-file" type="xs:string" use="optional" />
		<xs:attribute name="postion-template-name" type="xs:string" use="optional" />
		<xs:attribute name="position-template-file" type="xs:string" use="optional" />
		<xs:attribute name="size-template-name" type="xs:string" use="optional" />
		<xs:attribute name="size-template-file" type="xs:string" use="optional" />
	</xs:attributeGroup>
	<xs:group name="advancedgroup">
		<xs:sequence>
			<xs:element ref="parameter" maxOccurs="unbounded" minOccurs="0" />
			<xs:element ref="position-name" maxOccurs="1" minOccurs="1" />
			<xs:element ref="anchorpoint" maxOccurs="1" minOccurs="0" />
			<xs:element ref="position" maxOccurs="1" minOccurs="0" />
			<xs:element ref="z-index" maxOccurs="1" minOccurs="0" />
		</xs:sequence>
	</xs:group>
	<xs:attributeGroup name="advancedattributegroup">
		<xs:attribute name="class-name" type="xs:string" use="optional" />
		<xs:attribute name="prefix" type="xs:string" use="optional" />
		<xs:attribute name="super" type="xs:string" use="optional" />
		<xs:attribute name="generate-class" type="xs:boolean" use="optional" />
		<xs:attribute name="exported" type="xs:boolean" use="optional" />
	</xs:attributeGroup>
	<xs:simpleType name="uppertype">
		<xs:restriction base="xs:string">
    		<xs:pattern value="[A-Z]*"/>
 		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="vartype">
		<xs:restriction base="xs:string">
			<xs:pattern value="$\{[a-zA-Z_][a-zA-Z0-9_]*\}|[a-zA-Z_][a-zA-Z0-9_]*" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== tvd12/cocos2dx-v3/runtime-com.tvd.gameview.ext/TicTacToe/resources/xml/iPhonehd/won_offline_popup.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<view class-name="WonOfflinePopup" prefix="popup_won_offline" type="popup" exitable="true" 
		super="PopupLayer" background-name="default" size="261.0, 261.0"
		template-name="Common"
		exported="false"
		comment=""
		xmlns="http://www.tvd.com/tools"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.tvd.com/tools ../xsd/view_2_0.xsd">
	<position-name value="won_offline_popup" />
	<position value="default" />
	<define-path value="/Volumes/DATA/Working/TicTacToe/client/caroonline/CaroOnline/Classes/Other/Utils/Defines" />
	<parameters-path value="/Volumes/DATA/Working/TicTacToe/client/caroonline/CaroOnline/Classes/Other/Utils/GameParams" />
	<images-inputpath value="/Users/dungtavan/Desktop/Dialog/won_offline_popup" />
	<images-path value="/Volumes/DATA/Working/TicTacToe/client/caroonline/CaroOnline/Resources/iPhonehd" />
	<xibcontainer-path value="/Volumes/DATA/Working/TicTacToe/client/caroonline/CaroOnline/Resources/screenshots/iPhonehd" used="true" />
	<screencontainer-path value="/Volumes/DATA/Working/TicTacToe/client/caroonline/CaroOnline/Wireframing/WireframingScreen/iPhonehd" />
	<androidcontainer-path value="/Volumes/DATA/Working/TicTacToe/client/caroonline/CaroOnline/proj.android/res/layout/iPhonehd" />
	<class-path value="/Volumes/DATA/Working/TicTacToe/client/caroonline/CaroOnline/Classes/View/UI/Popup/Dialog" />
	<background-image id="won_offline_popup_background_won_offline_bg" 
		location-in-interfacebuilder="30.0, 153.0"
		width="261.0" height="261.0"
		phony-path="won_offline_popup/background/won_offline_bg.png"  />
	<exit-image position="0.0, 0.0" location-in-interfacebuilder="100.0, 100.0" />

	<sprites array="false" comment="create group of sprites">
		<sprite visible="true" comment="">
			<position-name value="won_offline_player" />
			<anchorpoint value="0.5, 0.5" />
			<position value="130.5, 191.5" />
			<z-index value="0" />
			<image id="won_offline_player" 
				location-in-interfacebuilder="132.0, 194.0"
				width="57.0" height="57.0"
				phony-path="main_game_layer/resource/main_symbol_x.png"  />
		</sprite>
	</sprites>
	<labels array="false" comment="create group of labels">
		<label visible="true" comment="">
			<text value="You win!" />
			<font name="HelveticaNeue" family="Helvetica Neue" />
			<font-color red="255" green="255" blue="255" alpha="255" />
			<font-size value="24.0" />
			<position-name value="notify" />
			<anchorpoint value="0.5, 0.5" />
			<position value="130.0, 143.0" />
			<location-in-interfacebuilder value="112.0, 259.0" />
			<z-index value="0" />
		</label>
		<label visible="true" comment="">
			<text value="GOOD LUCK NEXT TIME" />
			<font name="HelveticaNeue" family="Helvetica Neue" />
			<font-color red="255" green="255" blue="255" alpha="255" />
			<font-size value="13.0" />
			<position-name value="finish_title" />
			<anchorpoint value="0.5, 0.5" />
			<position value="130.0, 39.5" />
			<location-in-interfacebuilder value="78.0, 366.0" />
			<z-index value="0" />
		</label>
	</labels>
	<menuitems array="false" comment="create group of menuitems">
		<menuitem visible="true" comment="">
			<position-name value="finish" />
			<anchorpoint value="0.5, 0.5" />
			<position value="130.5, 39.5" />
			<z-index value="0" />
			<sprites array="false" comment="create group of sprites">
				<sprite visible="true" comment="">
					<position-name value="won_offline_finish_active" unlocated="true" />
					<image id="won_offline_popup_finish_won_offline_finish_active" 
						location-in-interfacebuilder="72.0, 352.0"
						width="177.0" height="45.0"
						phony-path="won_offline_popup/menuitems/finish/sprites/won_offline_finish_active.png"  />
				</sprite>
				<sprite visible="true" comment="">
					<position-name value="won_offline_finish_normal" unlocated="true" />
					<image id="won_offline_popup_finish_won_offline_finish_normal" 
						phony-path="won_offline_popup/menuitems/finish/sprites/won_offline_finish_normal.png"  />
				</sprite>
			</sprites>
		</menuitem>
	</menuitems>
	<resource comment="resource for view">
		<image id="won_offline_popup_resource_won_offline_finish_disable" 
			phony-path="won_offline_popup/resource/won_offline_finish_disable.png"  />
	</resource>
</view>

=== tvd12/cocos2dx-v3/runtime-New_configuration/SupernaturalMemory/resources/xml/iphone/main_game_layer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<view class-name="MainGameLayerView" prefix="layer_main_game" type="layer" exitable="false" 
		super="CommonLayer" background-name="default" size="320.0, 480.0"
		template-name="Common"
		exported="true"
		comment=""
		xmlns="http://www.tvd.com/tools"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.tvd.com/tools ../xsd/view_2_0.xsd">
	<position-name value="main_game_layer" />
	<position value="default" />
	<define-path value="/Volumes/Working/Bitbucket/supernatural-memory/supernatural-memory/SupernaturalMemory/Classes/Utils/Defines" />
	<parameters-path value="/Volumes/Working/Bitbucket/supernatural-memory/supernatural-memory/SupernaturalMemory/Classes/Utils/GameParams" />
	<images-inputpath value="/Volumes/Data/Storage/Images/supernatural-memory/main_game_layer" />
	<images-path value="/Volumes/Working/Bitbucket/supernatural-memory/supernatural-memory/SupernaturalMemory/Resources/iphone" />
	<xibcontainer-path value="/Volumes/Working/Bitbucket/supernatural-memory/supernatural-memory/SupernaturalMemory/Resources/screenshots/iphone" used="true" />
	<screencontainer-path value="/Volumes/Working/Bitbucket/supernatural-memory/supernatural-memory/SupernaturalMemory/Wireframing/WireframingScreen/iphone" />
	<androidcontainer-path value="/Volumes/Working/Bitbucket/supernatural-memory/supernatural-memory/SupernaturalMemory/proj.android/res/layout/iphone" />
	<class-path value="/Volumes/Working/Bitbucket/supernatural-memory/supernatural-memory/SupernaturalMemory/Classes/View/Layer" />

	<resource comment="resource for view">
		<image id="main_game_layer_resource_wood_back_active" 
			phony-path="main_game_layer/resource/wood_back_active.png"  />
		<image id="main_game_layer_resource_wood_back_normal" 
			phony-path="main_game_layer/resource/wood_back_normal.png"  />
		<image id="main_game_layer_resource_wood_bg" 
			phony-path="main_game_layer/resource/wood_bg.png"  />
		<image id="main_game_layer_resource_wood_fail_disable" 
			phony-path="main_game_layer/resource/wood_fail_disable.png"  />
		<image id="main_game_layer_resource_wood_replay_active" 
			phony-path="main_game_layer/resource/wood_replay_active.png"  />
		<image id="main_game_layer_resource_wood_replay_normal" 
			phony-path="main_game_layer/resource/wood_replay_normal.png"  />
		<image id="main_game_layer_resource_wood_screenshot" 
			phony-path="main_game_layer/resource/wood_screenshot.png"  />
		<image id="main_game_layer_resource_wood_setting_active" 
			phony-path="main_game_layer/resource/wood_setting_active.png"  />
		<image id="main_game_layer_resource_wood_setting_normal" 
			phony-path="main_game_layer/resource/wood_setting_normal.png"  />
		<image id="main_game_layer_resource_wood_square_default" 
			phony-path="main_game_layer/resource/wood_square_default.png"  />
		<image id="main_game_layer_resource_wood_square_text_disable" 
			phony-path="main_game_layer/resource/wood_square_text_disable.png"  />
		<image id="main_game_layer_resource_wood_suggest_active" 
			phony-path="main_game_layer/resource/wood_suggest_active.png"  />
		<image id="main_game_layer_resource_wood_suggest_normal" 
			phony-path="main_game_layer/resource/wood_suggest_normal.png"  />
	</resource>
</view>
